from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1812, 917)
        self.centralwidget = QtWidgets.QWidget(JarvisUi)
        self.centralwidget.setObjectName("centralwidget")
        self.GUI_5 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_5.setGeometry(QtCore.QRect(0, -10, 2211, 991))
        self.GUI_5.setText("")
        self.GUI_5.setPixmap(QtGui.QPixmap("../../B.G/Black_Template.jpg"))
        self.GUI_5.setScaledContents(True)
        self.GUI_5.setObjectName("GUI_5")
        self.GUI = QtWidgets.QLabel(self.centralwidget)
        self.GUI.setGeometry(QtCore.QRect(10, -50, 791, 231))
        self.GUI.setText("")
        self.GUI.setPixmap(QtGui.QPixmap("../../Extara Gui/ExtraGui/initial.gif"))
        self.GUI.setScaledContents(True)
        self.GUI.setObjectName("GUI")
        self.GUI_3 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_3.setGeometry(QtCore.QRect(1010,410, 291,241))
        self.GUI_3.setText("")
        self.GUI_3.setPixmap(QtGui.QPixmap("../../Extara Gui/ExtraGui/Earth_Template.gif"))
        self.GUI_3.setScaledContents(True)
        self.GUI_3.setObjectName("GUI_3")
        self.RecodGUI = QtWidgets.QLabel(self.centralwidget)
        self.RecodGUI.setGeometry(QtCore.QRect(-200, 420, 831, 521))
        self.RecodGUI.setText("")
        self.RecodGUI.setPixmap(QtGui.QPixmap("../../Voive R/VoiceReg/__1.gif"))
        self.RecodGUI.setScaledContents(True)
        self.RecodGUI.setObjectName("RecodGUI")
        self.GUI_6 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_6.setGeometry(QtCore.QRect(1000, 10, 301, 381))
        self.GUI_6.setText("")
        self.GUI_6.setPixmap(QtGui.QPixmap("../../../Downloads/O1SC.gif"))
        self.GUI_6.setScaledContents(True)
        self.GUI_6.setObjectName("GUI_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1330, 590, 481, 321))
        self.label_2.setStyleSheet("background-color: rgb(0, 10, 200);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.GUI_IRON_MAN_2 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_IRON_MAN_2.setGeometry(QtCore.QRect(1340, 600, 471, 311))
        self.GUI_IRON_MAN_2.setText("")
        self.GUI_IRON_MAN_2.setPixmap(QtGui.QPixmap("../../Extara Gui/ExtraGui/live.gif"))
        self.GUI_IRON_MAN_2.setScaledContents(True)
        self.GUI_IRON_MAN_2.setObjectName("GUI_IRON_MAN_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1310, -10, 521, 351))
        self.label_3.setStyleSheet("background-color: rgb(0, 10, 200);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.GUI_7 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_7.setGeometry(QtCore.QRect(1320, -10, 491, 341))
        self.GUI_7.setText("")
        self.GUI_7.setPixmap(QtGui.QPixmap("../../Extara Gui/ExtraGui/Hero_Template.gif"))
        self.GUI_7.setScaledContents(True)
        self.GUI_7.setObjectName("GUI_7")
        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(650, 130, 331, 61))
        self.text_time.setStyleSheet("background-color:Transparent;\n"
"font: 75 24pt \"Courier New\";\n"
"border-radius:none;\n"
"color:rgb(0, 255, 255);")
        self.text_time.setObjectName("text_time")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(620, 120, 371, 81))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("../../../Pictures/Screenshots/Screenshot_20230816_204707.png"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(620, 380, 371, 81))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("../../../Pictures/Screenshots/Screenshot_20230816_204707.png"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(620, 250, 371, 81))
        self.bg_3.setText("")
        self.bg_3.setPixmap(QtGui.QPixmap("../../../Pictures/Screenshots/Screenshot_20230816_204707.png"))
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")
        self.Text_Date = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date.setGeometry(QtCore.QRect(660, 280, 331, 61))
        self.Text_Date.setStyleSheet("background-color:Transparent;\n"
"font: 75 24pt \"Courier New\";\n"
"border-radius:none;\n"
"color:rgb(0, 255, 255);")
        self.Text_Date.setObjectName("Text_Date")
        self.GUI_4 = QtWidgets.QLabel(self.centralwidget)
        self.GUI_4.setGeometry(QtCore.QRect(0, 120, 611, 381))
        self.GUI_4.setText("")
        self.GUI_4.setPixmap(QtGui.QPixmap("../../Extara Gui/ExtraGui/B.G_Template_1.gif"))
        self.GUI_4.setScaledContents(True)
        self.GUI_4.setObjectName("GUI_4")
        self.Text_Date_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Date_2.setGeometry(QtCore.QRect(1290, 860, 331, 61))
        self.Text_Date_2.setStyleSheet("background-color:Transparent;\n"
"font: 75 24pt \"Courier New\";\n"
"border-radius:none;\n"
"color:rgb(0, 255, 255);")
        self.Text_Date_2.setObjectName("Text_Date_2")
        self.Text_Temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Temp.setGeometry(QtCore.QRect(660, 400, 331, 61))
        self.Text_Temp.setStyleSheet("background-color:Transparent;\n"
"font: 75 24pt \"Courier New\";\n"
"border-radius:none;\n"
"color:rgb(0, 255, 255);")
        self.Text_Temp.setObjectName("Text_Temp")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(430, 760, 391, 91))
        self.bg_4.setText("")
        self.bg_4.setPixmap(QtGui.QPixmap("../../../Pictures/Screenshots/Screenshot_20230816_204707.png"))
        self.bg_4.setScaledContents(True)
        self.bg_4.setObjectName("bg_4")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(460, 780, 351, 61))
        self.toolButton_2.setStyleSheet("background-color:Transparent;\n"
"font: 75 24pt \"Courier New\";\n"
"border-color: rgb(19, 6, 200);\n"
"color:rgb(38, 200, 48);")
        self.toolButton_2.setObjectName("toolButton_2")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(830, 760, 391, 91))
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap("../../../Pictures/Screenshots/Screenshot_20230816_204707.png"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(860, 780, 351, 61))
        self.toolButton_3.setStyleSheet("background-color:Transparent;\n"
"font: 75 24pt \"Courier New\";\n"
"\n"
"border-color: rgb(19, 6, 200);\n"
"color:rgb(38, 200, 48);")
        self.toolButton_3.setObjectName("toolButton_3")
        self.GUI_5.raise_()
        self.GUI.raise_()
        self.GUI_3.raise_()
        self.RecodGUI.raise_()
        self.GUI_6.raise_()
        self.label_2.raise_()
        self.GUI_IRON_MAN_2.raise_()
        self.label_3.raise_()
        self.GUI_7.raise_()
        self.bg.raise_()
        self.text_time.raise_()
        self.bg_2.raise_()
        self.bg_3.raise_()
        self.Text_Date.raise_()
        self.GUI_4.raise_()
        self.Text_Date_2.raise_()
        self.Text_Temp.raise_()
        self.bg_4.raise_()
        self.toolButton_2.raise_()
        self.bg_5.raise_()
        self.toolButton_3.raise_()
        JarvisUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "MainWindow"))
        self.toolButton_2.setText(_translate("JarvisUi", "start"))
        self.toolButton_3.setText(_translate("JarvisUi", "stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QMainWindow()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
